### ISSUE TITLE
chuck.xml depends on kamelet:chuck-norris-source

### ISSUE THREAD

**Issue by rbaumgar** [apache/camel-k-examples#83]
the chuck.xml depends on kamelet:chuck-norris-source, but this does not exist in the examples and is unavailable by default.

generic-examples/kamelets/chuck-norris/chuck.xml

chuck-noris-soure.kamelet..yaml

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: chuck-norris-source
  annotations:
    camel.apache.org/kamelet.support.level: "Stable"
    camel.apache.org/catalog.version: "main-SNAPSHOT"
    camel.apache.org/kamelet.icon: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iaXNvLTg4NTktMSI/Pg0KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDE5LjAuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPg0KPHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSJDYXBhXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4Ig0KCSB2aWV3Qm94PSIwIDAgNTEyIDUxMiIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgNTEyIDUxMjsiIHhtbDpzcGFjZT0icHJlc2VydmUiPg0KPHJlY3QgeD0iMTY1LjQ3IiB5PSIyNDMuOCIgc3R5bGU9ImZpbGw6I0YwRjBGQTsiIHdpZHRoPSIxMjkuNjUiIGhlaWdodD0iNDEuMiIvPg0KPGc+DQoJPHJlY3QgeD0iNDAzLjEyIiB5PSIxOTkuNjciIHN0eWxlPSJmaWxsOiNGRkI0ODc7IiB3aWR0aD0iMzIiIGhlaWdodD0iNDIiLz4NCgk8cmVjdCB4PSIyMTAuMTIiIHk9IjIwMy45NiIgc3R5bGU9ImZpbGw6I0ZGQjQ4NzsiIHdpZHRoPSIzMiIgaGVpZ2h0PSI0MiIvPg0KPC9nPg0KPGc+DQoJPHBhdGggc3R5bGU9ImZpbGw6I0YwRjBGQTsiIGQ9Ik0yNDIuOTU2LDE5NmwtNTcuODMzLTkwaC0yMS4xNzdjLTE5LjQzNSwwLTM2LjUyMywxMi44NjctNDEuODk0LDMxLjU0NWwtMjMuMDk1LDgwLjMxOQ0KCQlDOTMuNDY1LDIzNi45NjIsMTA3LjgsMjU2LDEyNy42NzIsMjU2aDgyLjQ1MXYtNjBoLTUyIi8+DQoJPHBhdGggc3R5bGU9ImZpbGw6I0YwRjBGQTsiIGQ9Ik0yMjYuNTA0LDE3MC4zOThMMjYwLjEyMywxMDZoMTcuMTI5YzE2LjQ4NCwwLDMxLjU1OCw5LjI5OCwzOC45NTYsMjQuMDI5bDIyLjA5NCw0My45OTcNCgkJYzMuNjg2LDcuMzQsMTEuMTk3LDExLjk3MywxOS40MTEsMTEuOTczaDQ1LjQxMXY3MC4xMjdIMjgyLjExIi8+DQo8L2c+DQo8cG9seWdvbiBzdHlsZT0iZmlsbDojQkVCRUJFOyIgcG9pbnRzPSIyMjYuNTA0LDE3MC4zOTggMTg1LjEyMywxMDYgMjU4Ljg0NSwxMDYgIi8+DQo8Zz4NCgk8cGF0aCBzdHlsZT0iZmlsbDojRDdEN0U2OyIgZD0iTTE2NS40NzQsMjg1bC01NS42OTUsMzIuMzQ3Yy0yMy41MDEsMTMuNjQ5LTQxLjIsMzUuNDItNDkuNzY1LDYxLjIxMkwzMi4zMDYsNDYyaDkzbDM1LTc4DQoJCUwxNjUuNDc0LDI4NXoiLz4NCgk8cGF0aCBzdHlsZT0iZmlsbDojRDdEN0U2OyIgZD0iTTI5NS4xMjMsMjg1bDU1LjY5NSwzMi4zNDdjMjMuNTAxLDEzLjY0OSw0MS4yLDM1LjQyLDQ5Ljc2NSw2MS4yMTJMNDI4LjI5MSw0NjJoLTkzbC0zNS03OA0KCQlMMjk1LjEyMywyODV6Ii8+DQo8L2c+DQo8Zz4NCgk8cGF0aCBzdHlsZT0iZmlsbDojQkVCRUJFOyIgZD0iTTIyLjg3Nyw1MDJoNzcuOTg3YzguMjg0LDAsMTUtNi43MTYsMTUtMTV2LTI1SDYyLjg3N0M0MC43ODYsNDYyLDIyLjg3Nyw0NzkuOTA5LDIyLjg3Nyw1MDINCgkJTDIyLjg3Nyw1MDJ6Ii8+DQoJPHBhdGggc3R5bGU9ImZpbGw6I0JFQkVCRTsiIGQ9Ik00MzcuNzE5LDUwMmgtNzcuOTg3Yy04LjI4NCwwLTE1LTYuNzE2LTE1LTE1di0yNWg1Mi45ODdDNDE5LjgxLDQ2Miw0MzcuNzE5LDQ3OS45MDksNDM3LjcxOSw1MDINCgkJTDQzNy43MTksNTAyeiIvPg0KPC9nPg0KPGc+DQoJPHBhdGggc3R5bGU9ImZpbGw6I0ZGQ0RBQzsiIGQ9Ik0yMjYuNTA0LDEwNkwyMjYuNTA0LDEwNmMtMjQuMzAxLDAtNDQtMTkuNjk5LTQ0LTQ0di04YzAtMjQuMzAxLDE5LjY5OS00NCw0NC00NGwwLDANCgkJYzI0LjMwMSwwLDQ0LDE5LjY5OSw0NCw0NHY4QzI3MC41MDQsODYuMzAxLDI1MC44MDUsMTA2LDIyNi41MDQsMTA2eiIvPg0KCTxwYXRoIHN0eWxlPSJmaWxsOiNGRkNEQUM7IiBkPSJNNDcwLjEyMywyNTEuODMzaC0xNmMtMTAuNDkzLDAtMTktOC41MDctMTktMTlWMjA4LjVjMC0xMC40OTMsOC41MDctMTksMTktMTloMTYNCgkJYzEwLjQ5MywwLDE5LDguNTA3LDE5LDE5djI0LjMzM0M0ODkuMTIzLDI0My4zMjcsNDgwLjYxNiwyNTEuODMzLDQ3MC4xMjMsMjUxLjgzM3oiLz4NCgk8cGF0aCBzdHlsZT0iZmlsbDojRkZDREFDOyIgZD0iTTI3Ny4xMjMsMjU2LjEyN2gtMTZjLTEwLjQ5MywwLTE5LTguNTA3LTE5LTE5di0yNC4zMzNjMC0xMC40OTMsOC41MDctMTksMTktMTloMTYNCgkJYzEwLjQ5MywwLDE5LDguNTA3LDE5LDE5djI0LjMzM0MyOTYuMTIzLDI0Ny42MiwyODcuNjE2LDI1Ni4xMjcsMjc3LjEyMywyNTYuMTI3eiIvPg0KPC9nPg0KPHBvbHlnb24gc3R5bGU9ImZpbGw6I0YwRjBGQTsiIHBvaW50cz0iMTM0LjQ3NCwzODQgMTY1LjQ3NCwyODUgMjk1LjEyMywyODUgMzI2LjEyMywzODQgIi8+DQo8cGF0aCBkPSJNMjUxLjcsMzM0Yy0yLjYzLDAtNS4yMSwxLjA3LTcuMDcsMi45M2MtMS44NiwxLjg2LTIuOTMsNC40NC0yLjkzLDcuMDdzMS4wNyw1LjIxLDIuOTMsNy4wN3M0LjQ0LDIuOTMsNy4wNywyLjkzDQoJczUuMjEtMS4wNyw3LjA3LTIuOTNzMi45My00LjQ0LDIuOTMtNy4wN3MtMS4wNi01LjIxLTIuOTMtNy4wN0MyNTYuOTEsMzM1LjA3LDI1NC4zMywzMzQsMjUxLjcsMzM0eiIvPg0KPHBhdGggZD0iTTM5Ny40MzksMzY5LjA2NmMtNS4yNDMsMS43MzYtOC4wODUsNy4zOTQtNi4zNSwxMi42MzdsMC4xNDgsMC40NDdjMS4zOTEsNC4yLDUuMjk3LDYuODU5LDkuNDkyLDYuODU5DQoJYzEuMDQyLDAsMi4xMDItMC4xNjUsMy4xNDUtMC41MWM1LjI0My0xLjczNiw4LjA4NS03LjM5NCw2LjM1LTEyLjYzN2wtMC4xNDgtMC40NDdDNDA4LjM0LDM3MC4xNzIsNDAyLjY4MiwzNjcuMzMxLDM5Ny40MzksMzY5LjA2Ng0KCXoiLz4NCjxwYXRoIGQ9Ik00NzAuMTIzLDE3OS41aC0xNmMtOC44MDYsMC0xNi43MDIsMy45NTEtMjIuMDI1LDEwLjE2N2gtMTguOTc1VjE4NmMwLTUuNTIzLTQuNDc3LTEwLTEwLTEwaC00NS40MTENCgljLTQuNDU5LDAtOC40NzMtMi40NzYtMTAuNDc1LTYuNDYxbC0yMi4wOTQtNDMuOTk3QzMxNS45OTMsMTA3LjMyLDI5Ny42NDIsOTYsMjc3LjI1MSw5NmgtOC44MzUNCgljNy41NTEtOS4yOSwxMi4wODctMjEuMTIzLDEyLjA4Ny0zNHYtOGMwLTI5Ljc3Ni0yNC4yMjQtNTQtNTQtNTRzLTU0LDI0LjIyNC01NCw1NHY4YzAsMTIuODc3LDQuNTM3LDI0LjcxLDEyLjA4OCwzNGgtMjAuNjQ2DQoJYy0yMy43NTksMC00NC45MzgsMTUuOTQ4LTUxLjUwNCwzOC43ODFMODkuMzQ2LDIxNS4xYy0zLjQ5NCwxMi4xNDktMS4xMzYsMjQuOTEsNi40NjgsMzUuMDA4DQoJYzcuNjA1LDEwLjEsMTkuMjE3LDE1Ljg5MiwzMS44NTgsMTUuODkyaDI3LjgwMXYxMy4yNDNMMTA0Ljc1NiwzMDguN2MtMjUuNjMxLDE0Ljg4Ny00NC44OTIsMzguNTc4LTU0LjIzMiw2Ni43MDhsLTI3LjcwOCw4My40NDENCgljLTEuMDEzLDMuMDQ5LTAuNDk5LDYuMzk4LDEuMzgxLDkuMDAzYzAuMzI1LDAuNDUxLDAuNjk1LDAuODU3LDEuMDgzLDEuMjQxYy03LjcxMiw4LjgwMS0xMi40MDMsMjAuMzEzLTEyLjQwMywzMi45MDcNCgljMCw1LjUyMyw0LjQ3NywxMCwxMCwxMGg3Ny45ODdjMTMuNzg1LDAsMjUtMTEuMjE1LDI1LTI1di0xNS4wNDFjMy43MTMtMC4yMDksNy4wMjktMi40NDQsOC41NjQtNS44NjVMMTY2Ljc3OSwzOTRoMTI3LjAzOA0KCWwzMi4zNSw3Mi4wOTRjMS41MzUsMy40MjEsNC44NTEsNS42NTYsOC41NjQsNS44NjVWNDg3YzAsMS43MTIsMC4xNzQsMy4zODQsMC41MDMsNWgtODMuNTMzYy01LjUyMywwLTEwLDQuNDc3LTEwLDEwDQoJczQuNDc3LDEwLDEwLDEwaDE4Ni4wMThjNS41MjMsMCwxMC00LjQ3NywxMC0xMGMwLTEyLjU5NC00LjY5LTI0LjEwNy0xMi40MDMtMzIuOTA3YzAuMzg4LTAuMzg1LDAuNzU4LTAuNzkxLDEuMDgzLTEuMjQxDQoJYzEuODgtMi42MDUsMi4zOTQtNS45NTQsMS4zODEtOS4wMDNsLTE2LjgwNS01MC42MDZjLTEuNzQtNS4yNDEtNy4zOTctOC4wOC0xMi42NDItNi4zMzljLTUuMjQyLDEuNzQtOC4wOCw3LjQtNi4zMzksMTIuNjQyDQoJTDQxNC40MzMsNDUyaC0xNi43MTRoLTUyLjk4OGgtMi45NjdsLTI2LjAyNi01OGgxMC4zODVjMy4xODIsMCw2LjE3NC0xLjUxNSw4LjA1OS00LjA3OXMyLjQzNi01Ljg3MywxLjQ4NC04LjkwOWwtMjMuMzA5LTc0LjQzOA0KCWwzMy40MzksMTkuNDIxYzEyLjc0MSw3LjQsMjMuOTE5LDE3LjcwNiwzMi4zMjgsMjkuODAyYzEuOTQzLDIuNzk1LDUuMDU2LDQuMjkzLDguMjIsNC4yOTNjMS45NjksMCwzLjk1OS0wLjU4MSw1LjY5OS0xLjc5DQoJYzQuNTM1LTMuMTUyLDUuNjU2LTkuMzg0LDIuNTA0LTEzLjkxOWMtMTAuMDY3LTE0LjQ4My0yMy40NTItMjYuODIyLTM4LjcwNi0zNS42ODJsLTUwLjcxOC0yOS40NTZ2LTEzLjExNmg5OA0KCWM1LjUyMywwLDEwLTQuNDc3LDEwLTEwdi00LjQ2aDE4Ljk3NGM1LjMyMyw2LjIxNiwxMy4yMTksMTAuMTY3LDIyLjAyNiwxMC4xNjdoMTZjMTUuOTkxLDAsMjktMTMuMDA5LDI5LTI5VjIwOC41DQoJQzQ5OS4xMjMsMTkyLjUwOSw0ODYuMTEzLDE3OS41LDQ3MC4xMjMsMTc5LjV6IE0zOTcuNzE5LDQ3MmMxMy4wMzgsMCwyNC4xNTksOC4zNTksMjguMjg3LDIwaC02Ni4yNzRjLTIuNzU3LDAtNS0yLjI0My01LTV2LTE1DQoJSDM5Ny43MTl6IE0yODYuMTIzLDIzNy4xMjdjMCw0Ljk2Mi00LjAzOCw5LTksOWgtMTZjLTQuOTYyLDAtOS00LjAzOC05LTl2LTI0LjMzM2MwLTQuOTYyLDQuMDM4LTksOS05aDE2YzQuOTYyLDAsOSw0LjAzOCw5LDkNCglWMjM3LjEyN3ogTTIyMC4xMjMsMjEzLjk2aDEydjIyaC0xMlYyMTMuOTZ6IE0xOTguMzIsMTA4LjA0YzguMjEsNS4wNDUsMTcuODYyLDcuOTYsMjguMTg1LDcuOTZjNi42NDgsMCwxMy4wMTctMS4yMTUsMTguOTA0LTMuNDIzDQoJbC0xOS44LDM3LjkyOEwxOTguMzIsMTA4LjA0eiBNMTkyLjUwNCw1NGMwLTE4Ljc0OCwxNS4yNTItMzQsMzQtMzRjMTguNzQ4LDAsMzQsMTUuMjUyLDM0LDM0djhjMCwxOC43NDgtMTUuMjUyLDM0LTM0LDM0bDAsMA0KCWMtMTguNzQ4LDAtMzQtMTUuMjUyLTM0LTM0VjU0eiBNMTExLjc5MiwyMzguMDc5Yy0zLjc5MS01LjAzNC00Ljk2Ni0xMS4zOTUtMy4yMjUtMTcuNDUxbDIzLjA5Ni04MC4zMg0KCWM0LjExNS0xNC4zMTIsMTcuMzktMjQuMzA4LDMyLjI4My0yNC4zMDhoMTUuNzE2bDUwLjA5Nyw3Ny45NmgtOS44NDZjLTAuOTQyLTQuNTQ1LTQuOTY3LTcuOTYtOS43OTEtNy45NmgtNTINCgljLTUuNTIzLDAtMTAsNC40NzctMTAsMTBzNC40NzcsMTAsMTAsMTBoNDJ2MzkuOTZWMjQ2aC03Mi40NUMxMjEuMzcxLDI0NiwxMTUuNTgzLDI0My4xMTMsMTExLjc5MiwyMzguMDc5eiBNMTA1Ljg2NSw0ODcNCgljMCwyLjc1Ny0yLjI0Myw1LTUsNUgzNC41OTFjNC4xMjctMTEuNjQxLDE1LjI0OS0yMCwyOC4yODctMjBoNDIuOTg3VjQ4N3ogTTExOC44MzIsNDUyaC0yLjk2N0g2Mi44NzdINDYuMTYzbDIzLjM0MS03MC4yOQ0KCWM3LjgwMi0yMy40OTUsMjMuODg5LTQzLjI4Miw0NS4yOTctNTUuNzE2bDMzLjQzOS0xOS40MjFsLTIzLjMwOSw3NC40MzhjLTAuOTUxLDMuMDM3LTAuNCw2LjM0NSwxLjQ4NCw4LjkwOQ0KCWMxLjg4NCwyLjU2NCw0Ljg3Niw0LjA3OSw4LjA1OSw0LjA3OWgxMC4zODRMMTE4LjgzMiw0NTJ6IE0xNDguMDg0LDM3NGw2LjI2My0yMGg1OC4xYzUuNTIzLDAsMTAtNC40NzcsMTAtMTBzLTQuNDc3LTEwLTEwLTEwDQoJaC01MS44MzhsMTIuMjEyLTM5aDExNC45NTRsMjQuNzM4LDc5SDE0OC4wODR6IE0yODUuMTIzLDI3NUgxNzUuNDc0di05aDM0LjY0OWM1LjUyMywwLDEwLTQuNDc3LDEwLTEwdi0wLjA0aDE4Ljk3NQ0KCWM1LjMyMyw2LjIxNiwxMy4yMTksMTAuMTY3LDIyLjAyNSwxMC4xNjdoMTZjMS4wNjcsMCwyLjEyLTAuMDYyLDMuMTU3LTAuMTc1YzAuNTk0LDAuMTEsMS4yMDUsMC4xNzUsMS44MzEsMC4xNzVoMy4wMTJMMjg1LjEyMywyNzUNCglMMjg1LjEyMywyNzV6IE0zOTMuMTIzLDI0Ni4xMjdoLTg4LjQzN2MwLjkyOC0yLjgzNSwxLjQzNy01Ljg1OSwxLjQzNy05di0yNC4zMzNjMC0xNS45OTEtMTMuMDA5LTI5LTI5LTI5aC0xNg0KCWMtNC40MTQsMC04LjU5OCwwLjk5NS0xMi4zNDYsMi43NjdsLTEwLjcyLTE2LjY4M0wyNjYuMTgzLDExNmgxMS4wNjljMTIuNzgxLDAsMjQuMjgzLDcuMDk1LDMwLjAxOSwxOC41MTdsMjIuMDk0LDQzLjk5Nw0KCUMzMzQuNzgsMTg5LjMsMzQ1LjY0MywxOTYsMzU3LjcxMiwxOTZoMzUuNDExdjMuNjY3djQyTDM5My4xMjMsMjQ2LjEyN0wzOTMuMTIzLDI0Ni4xMjd6IE00MTMuMTIzLDIwOS42NjdoMTJ2MjJoLTEyVjIwOS42Njd6DQoJIE00NzkuMTIzLDIzMi44MzNjMCw0Ljk2Mi00LjAzOCw5LTksOWgtMTZjLTQuOTYyLDAtOS00LjAzOC05LTlWMjA4LjVjMC00Ljk2Miw0LjAzOC05LDktOWgxNmM0Ljk2MiwwLDksNC4wMzgsOSw5VjIzMi44MzN6Ii8+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8L3N2Zz4NCg==
    camel.apache.org/provider: "Apache Software Foundation"
    camel.apache.org/kamelet.group: "Chuck Norris"
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "Chuck Norris Source"
    description: |-
      Gets periodically Chuck Norris jokes
    type: object
    properties:
      period:
        title: Period
        description: The interval (msec) to wait before getting the next joke
        type: integer
        default: 10000
  types:
    out:
      mediaType: text/plain
  dependencies:
    - "camel:kamelet"
    - "camel:timer"
    - "camel:http"
    - "camel:jsonpath"
  template:
    from:
      uri: "timer:chuck"
      parameters:
        period: "{{period}}"
      steps:
        - to: "https://api.chucknorris.io/jokes/random"
        - set-body:
            jsonpath: "$.value"
        - to: "kamelet:sink"

```
